[package]
name = "belajar-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "01_dasar"
path = "01_dasar/main.rs"

[[bin]]
name = "02_struktur_data"
path = "02_struktur_data/main.rs"

[[bin]]
name = "03_fungsi"
path = "03_fungsi/main.rs"

[[bin]]
name = "04_enum"
path = "04_enum/main.rs"

[[bin]]
name = "05_traits"
path = "05_traits/main.rs"

[[bin]]
name = "06_generics"
path = "06_generics/main.rs"

[[bin]]
name = "07_lifetime"
path = "07_lifetime/main.rs"

[[bin]]
name = "08_error_handling"
path = "08_error_handling/main.rs"

[[bin]]
name = "09_modules"
path = "09_modules/main.rs"

[[bin]]
name = "10_smart_pointers"
path = "10_smart_pointers/main.rs"

[[bin]]
name = "11_iterators"
path = "11_iterators/main.rs"

[[bin]]
name = "12_testing"
path = "12_testing/main.rs"

[[bin]]
name = "13_concurrency"
path = "13_concurrency/main.rs"

[[bin]]
name = "14_string_file_io"
path = "14_string_file_io/main.rs"

[[bin]]
name = "15_std_collections"
path = "15_std_collections/main.rs"

[[bin]]
name = "16_async_await"
path = "16_async_await/main.rs"

[[bin]]
name = "17_macros"
path = "17_macros/main.rs"
